# Basic
title: Root
subtitle: blog
description: .... . .-.. .-.. --- -....- .-- --- .-. -..
# 头像里面的标题
avatarTitle: hacker
# 头像里面的描述
avatarDesc: I am root.
url: "https://rooaw.github.io/"

# 博客是否自动生成目录，false为不生成
enableToc: true

# Comment
comment:
    # livere: MTAyMC81MDk5NC8yNzQ3Ng  # https://www.livere.com
    disqus: 
    # uyan: 2143225  # 有言id,登录有言官网申请

# Social
social:
    weibo:  
    github: 
    # zhihu: panpanleopard
    # juejin: xxx
    jianshu: 
    # twitter: 
    mail: csq945@qq.com


# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id:   

# Google Analytics
# 使用博客模板请去掉或者更换 id
ga:
    id:  
    host:   


# 《----------------- 上面的信息修改成你自己的 ---------------------------》
#
#
#  _post/ 下的文章更换成你自己的文章
#  帮忙star一下，感谢~😆 地址： https://github.com/leopardpan/leopardpan.github.io
#
#
# 《--------------- 下面的信息可以自行选择是否修改 ------------------------》


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: Home

# Navigation buttons in the front page.s
nav:
    - {title: Archive, description: archive, url: '/archive'}   
    - {title: Tags, description: tags, url: '/tags'}      
    - {title: About, description: about, url: '/about'}   
    

# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 20
paginate_path: "page/:num/"


